### ISSUE TITLE
PMC11100790: Section is not linking correctly

### ISSUE THREAD

**Issue by rowanc1** [continuous-foundation/jats#46]
Methods isn't linked.

![image](https://github.com/user-attachments/assets/cf1ec65e-4ec4-4710-8878-c892efb03ebd)

ID: PMC11100790

**Comment by rowanc1** [comment]
I think this is all biorxiv papers?

**Comment by fwkoch** [comment]
Addressed by #50 

<img width="662" alt="image" src="https://github.com/user-attachments/assets/f943ae4f-49c2-45b2-8a45-81390166c56a">
